---
language: php
php:
  - "7.1"
  - nightly
install: composer install --ignore-platform-reqs
script:
  - >-
    test "$TRAVIS_PHP_VERSION" = nightly ||
    vendor/bin/php-cs-fixer fix
    --config=.php_cs.dist
    --dry-run
    --path-mode=intersection
    --using-cache=no
    --verbose
    $(git diff --diff-filter=d --name-only $TRAVIS_COMMIT_RANGE)
  - vendor/bin/phpunit
